#!/usr/bin/env python3
"""Validate a project-plan JSON file and build deterministic offline artifacts."""

from __future__ import annotations

import argparse
import heapq
import html
import json
import math
import os
from pathlib import Path
import sys
import tempfile
import unicodedata
from typing import Any


GENERATOR = "project-planner/build_plan.py"
GENERATED_MARKER = f"Generated by {GENERATOR}"
OUTPUT_NAMES = ("schedule.json", "gantt.svg", "gantt.html", "plan.md")
DEFAULT_UNIT = "相对工作单位"


class PlanError(Exception):
    """An error that should be shown to a CLI user without a traceback."""


def _is_number(value: Any) -> bool:
    return isinstance(value, (int, float)) and not isinstance(value, bool)


def _finite_nonnegative(value: Any) -> bool:
    if not _is_number(value):
        return False
    try:
        return math.isfinite(float(value)) and value >= 0
    except (OverflowError, ValueError):
        return False


def _require_keys(obj: dict[str, Any], keys: tuple[str, ...], where: str, errors: list[str]) -> None:
    for key in keys:
        if key not in obj:
            errors.append(f"{where} 缺少字段 {key!r}")


def _string_list(value: Any, where: str, errors: list[str], *, nonempty: bool = False) -> list[str]:
    if not isinstance(value, list):
        errors.append(f"{where} 必须是字符串数组")
        return []
    result: list[str] = []
    for index, item in enumerate(value):
        if not isinstance(item, str) or (nonempty and not item.strip()):
            errors.append(f"{where}[{index}] 必须是{'非空' if nonempty else ''}字符串")
        else:
            result.append(item)
    if len(result) != len(set(result)):
        errors.append(f"{where} 不允许重复项")
    return result


def validate_plan(raw: Any) -> dict[str, Any]:
    """Return a normalized plan, or raise PlanError with all useful validation errors."""
    if not isinstance(raw, dict):
        raise PlanError("输入 JSON 顶层必须是对象")
    errors: list[str] = []
    required = ("version", "title", "summary", "assumptions", "risks", "requirements", "max_parallel", "tasks")
    _require_keys(raw, required, "顶层", errors)

    if type(raw.get("version")) is not int or raw.get("version") != 1:
        errors.append("version 必须严格等于整数 1")
    title = raw.get("title")
    if not isinstance(title, str) or not title.strip():
        errors.append("title 必须是非空字符串")
    if not isinstance(raw.get("summary"), str):
        errors.append("summary 必须是字符串")
    unit = raw.get("unit", DEFAULT_UNIT)
    if not isinstance(unit, str) or not unit.strip():
        errors.append("unit 必须是非空字符串")
    assumptions = _string_list(raw.get("assumptions"), "assumptions", errors)
    risks = _string_list(raw.get("risks"), "risks", errors)

    max_parallel = raw.get("max_parallel")
    if max_parallel is not None and (
        not isinstance(max_parallel, int) or isinstance(max_parallel, bool) or max_parallel <= 0
    ):
        errors.append("max_parallel 必须是正整数或 null（未知）")

    requirements_raw = raw.get("requirements")
    requirements: list[dict[str, str]] = []
    requirement_ids: set[str] = set()
    if not isinstance(requirements_raw, list):
        errors.append("requirements 必须是数组")
    else:
        for index, req in enumerate(requirements_raw):
            where = f"requirements[{index}]"
            if not isinstance(req, dict):
                errors.append(f"{where} 必须是对象")
                continue
            _require_keys(req, ("id", "text", "source"), where, errors)
            req_id = req.get("id")
            if not isinstance(req_id, str) or not req_id.strip():
                errors.append(f"{where}.id 必须是非空字符串")
            elif req_id in requirement_ids:
                errors.append(f"需求 ID 重复: {req_id}")
            else:
                requirement_ids.add(req_id)
            for key in ("text", "source"):
                if not isinstance(req.get(key), str):
                    errors.append(f"{where}.{key} 必须是字符串")
            if isinstance(req_id, str) and isinstance(req.get("text"), str) and isinstance(req.get("source"), str):
                requirements.append({"id": req_id, "text": req["text"], "source": req["source"]})

    tasks_raw = raw.get("tasks")
    tasks: list[dict[str, Any]] = []
    task_ids: set[str] = set()
    task_fields = (
        "id", "title", "description", "requirement_ids", "duration", "depends_on", "resources",
        "deliverable", "acceptance", "estimate_basis", "kind", "external_ready", "pr_scope",
    )
    if not isinstance(tasks_raw, list):
        errors.append("tasks 必须是数组")
    else:
        for index, task in enumerate(tasks_raw):
            where = f"tasks[{index}]"
            if not isinstance(task, dict):
                errors.append(f"{where} 必须是对象")
                continue
            _require_keys(task, task_fields, where, errors)
            task_id = task.get("id")
            if not isinstance(task_id, str) or not task_id.strip():
                errors.append(f"{where}.id 必须是非空字符串")
            elif task_id in task_ids:
                errors.append(f"任务 ID 重复: {task_id}")
            else:
                task_ids.add(task_id)
            for key in ("title", "description", "deliverable", "estimate_basis", "pr_scope"):
                value = task.get(key)
                if not isinstance(value, str) or (key == "title" and not value.strip()):
                    errors.append(f"{where}.{key} 必须是{'非空' if key == 'title' else ''}字符串")
            req_ids = _string_list(task.get("requirement_ids"), f"{where}.requirement_ids", errors, nonempty=True)
            deps = _string_list(task.get("depends_on"), f"{where}.depends_on", errors, nonempty=True)
            resources = _string_list(task.get("resources"), f"{where}.resources", errors, nonempty=True)
            acceptance = _string_list(task.get("acceptance"), f"{where}.acceptance", errors)
            kind = task.get("kind")
            if kind not in ("task", "milestone", "external"):
                errors.append(f"{where}.kind 必须是 task、milestone 或 external")
            duration = task.get("duration")
            if not _finite_nonnegative(duration):
                errors.append(f"{where}.duration 必须是有限非负数")
            elif kind in ("milestone", "external") and duration != 0:
                errors.append(f"{where}.duration 在 milestone 或 external 类型下必须为 0")
            elif kind == "task" and duration == 0:
                errors.append(f"{where}.duration 在 task 类型下必须大于 0")
            external_ready = task.get("external_ready")
            if kind == "external":
                if external_ready is not None and not _finite_nonnegative(external_ready):
                    errors.append(f"{where}.external_ready 必须是有限非负数或 null")
            elif external_ready is not None:
                errors.append(f"{where}.external_ready 仅 external 可设置；其他类型必须为 null")
            if isinstance(task_id, str):
                tasks.append({
                    "id": task_id,
                    "title": task.get("title"),
                    "description": task.get("description"),
                    "requirement_ids": req_ids,
                    "duration": duration,
                    "depends_on": deps,
                    "resources": resources,
                    "deliverable": task.get("deliverable"),
                    "acceptance": acceptance,
                    "estimate_basis": task.get("estimate_basis"),
                    "kind": kind,
                    "external_ready": external_ready,
                    "pr_scope": task.get("pr_scope"),
                })

    for task in tasks:
        for dep in task["depends_on"]:
            if dep not in task_ids:
                errors.append(f"任务 {task['id']} 引用了未知依赖 {dep}")
        for req_id in task["requirement_ids"]:
            if req_id not in requirement_ids:
                errors.append(f"任务 {task['id']} 引用了未知需求 {req_id}")

    covered = {req_id for task in tasks for req_id in task["requirement_ids"]}
    for req_id in sorted(requirement_ids - covered):
        errors.append(f"需求未被任何任务覆盖: {req_id}")

    if not errors and tasks:
        _topological_order(tasks)  # Raises a precise cycle error.
    if errors:
        raise PlanError("输入校验失败：\n- " + "\n- ".join(errors))
    return {
        "version": 1,
        "title": title,
        "summary": raw["summary"],
        "unit": unit,
        "assumptions": assumptions,
        "risks": risks,
        "requirements": requirements,
        "max_parallel": max_parallel,
        "tasks": tasks,
    }


def _topological_order(tasks: list[dict[str, Any]]) -> list[str]:
    index = {task["id"]: i for i, task in enumerate(tasks)}
    indegree = {task["id"]: len(task["depends_on"]) for task in tasks}
    children = {task["id"]: [] for task in tasks}
    for task in tasks:
        for dep in task["depends_on"]:
            children[dep].append(task["id"])
    ready = [(index[task_id], task_id) for task_id, degree in indegree.items() if degree == 0]
    heapq.heapify(ready)
    order: list[str] = []
    while ready:
        _, task_id = heapq.heappop(ready)
        order.append(task_id)
        for child in children[task_id]:
            indegree[child] -= 1
            if indegree[child] == 0:
                heapq.heappush(ready, (index[child], child))
    if len(order) != len(tasks):
        remaining = [task["id"] for task in tasks if indegree[task["id"]] > 0]
        raise PlanError("依赖图存在循环，涉及任务: " + ", ".join(remaining))
    return order


def build_schedule(plan: dict[str, Any]) -> dict[str, Any]:
    tasks = plan["tasks"]
    task_map = {task["id"]: task for task in tasks}
    topo = _topological_order(tasks)

    blocked_by: dict[str, set[str]] = {task["id"]: set() for task in tasks}
    for task_id in topo:
        task = task_map[task_id]
        if task["kind"] == "external" and task["external_ready"] is None:
            blocked_by[task_id].add(task_id)
        for dep in task["depends_on"]:
            blocked_by[task_id].update(blocked_by[dep])

    scheduled: dict[str, dict[str, float]] = {}
    pending = [task["id"] for task in tasks if not blocked_by[task["id"]]]
    current = 0.0
    while pending:
        active = lambda: [
            task_map[task_id] for task_id, timing in scheduled.items()
            if task_map[task_id]["kind"] == "task" and timing["start"] <= current
            and timing["finish"] > current
        ]
        # Re-scan at the same event time. A zero-duration node may release an
        # earlier input-order task, and that dependent must not wait for a later event.
        while True:
            pass_started = False
            for task_id in list(pending):
                task = task_map[task_id]
                if any(dep not in scheduled or scheduled[dep]["finish"] > current for dep in task["depends_on"]):
                    continue
                if task["kind"] == "external" and task["external_ready"] > current:
                    continue
                if task["kind"] == "task":
                    running = active()
                    if plan["max_parallel"] is not None and len(running) >= plan["max_parallel"]:
                        continue
                    held = {resource for active_task in running for resource in active_task["resources"]}
                    if held.intersection(task["resources"]):
                        continue
                start = current
                finish = start + float(task["duration"])
                scheduled[task_id] = {"start": start, "finish": finish}
                pending.remove(task_id)
                pass_started = True
            if not pass_started:
                break
        if pending:
            future = [timing["finish"] for timing in scheduled.values() if timing["finish"] > current]
            for task_id in pending:
                task = task_map[task_id]
                if task["kind"] == "external" and task["external_ready"] is not None and task["external_ready"] > current:
                    future.append(float(task["external_ready"]))
            if not future:
                raise PlanError("内部排程错误：存在无法推进且未标记为阻塞的任务")
            current = min(future)

    output_tasks: list[dict[str, Any]] = []
    for input_index, task in enumerate(tasks):
        result = dict(task)
        result["input_index"] = input_index
        if blocked_by[task["id"]]:
            result.update({
                "status": "blocked",
                "start": None,
                "finish": None,
                "blocked_by": sorted(blocked_by[task["id"]]),
            })
        else:
            result.update({
                "status": "scheduled",
                "start": scheduled[task["id"]]["start"],
                "finish": scheduled[task["id"]]["finish"],
                "blocked_by": [],
            })
        output_tasks.append(result)

    makespan = max((item["finish"] for item in output_tasks if item["finish"] is not None), default=0.0)
    return {
        "generator": GENERATOR,
        "version": plan["version"],
        "title": plan["title"],
        "summary": plan["summary"],
        "unit": plan["unit"],
        "assumptions": plan["assumptions"],
        "risks": plan["risks"],
        "requirements": plan["requirements"],
        "max_parallel": plan["max_parallel"],
        "scheduling": {
            "strategy": "deterministic_topological_list_scheduling",
            "priority": "input_order",
            "dependency_release": "finish",
            "resource_semantics": "exact_string_exclusive_for_task_kind",
            "capacity_semantics": "unbounded_when_null" if plan["max_parallel"] is None else "bounded_task_kind_only",
            "optimality": "heuristic_not_globally_optimal",
            "makespan": makespan,
        },
        "tasks": output_tasks,
    }


def _fmt_time(value: Any) -> str:
    if value is None:
        return "—"
    number = float(value)
    if number.is_integer():
        return f"T+{int(number)}"
    return f"T+{number:.12g}"


def _md(value: Any) -> str:
    text = _clean_text(value)
    for old, new in (("&", "&amp;"), ("<", "&lt;"), (">", "&gt;"), ("\\", "\\\\"),
                     ("|", "\\|"), ("`", "\\`"), ("[", "\\["), ("]", "\\]")):
        text = text.replace(old, new)
    return text.replace("\r\n", "<br>").replace("\n", "<br>").replace("\r", "<br>")


def _list_or_none(items: list[str]) -> str:
    return "、".join(_md(item) for item in items) if items else "无"


def _clean_text(value: Any) -> str:
    """Replace characters that are invalid in XML/HTML text nodes."""
    return "".join(
        char if char in "\t\n\r" or ord(char) >= 32 else "�"
        for char in str(value)
    )


def _html(value: Any) -> str:
    return html.escape(_clean_text(value), quote=True)


def _ellipsize(value: Any, max_units: int) -> str:
    """Fit mixed CJK/Latin labels into a predictable SVG text budget."""
    text = str(value)
    units = 0
    result: list[str] = []
    for char in text:
        width = 2 if unicodedata.east_asian_width(char) in ("W", "F", "A") else 1
        if units + width > max_units:
            return "".join(result).rstrip() + "…"
        result.append(char)
        units += width
    return text


def render_markdown(schedule: dict[str, Any]) -> str:
    capacity = "未知；排程按无容量上限处理" if schedule["max_parallel"] is None else str(schedule["max_parallel"])
    lines = [
        f"<!-- {GENERATED_MARKER} -->", "", "# 项目计划", "", f"**标题：** {_md(schedule['title'])}", "",
        f"**摘要：** {_md(schedule['summary'])}", "", f"**工作量单位：** {_md(schedule['unit'])}", "",
        f"**并行容量：** {capacity}", "", "任务工作量为粗略估算；`T+N` 表示相对位置，不换算为小时、工作日或实际工期。普通任务条长表示工作量；阻塞任务的整行条纹只表示状态。",
        "", "排程使用输入任务顺序作为稳定优先级，依赖在前置任务结束时释放；结果是确定性的列表调度，不保证全局最优。",
        "", "## 假设", "",
    ]
    lines.extend(f"- {_md(item)}" for item in schedule["assumptions"] or ["无"])
    lines.extend(["", "## 风险", ""])
    lines.extend(f"- {_md(item)}" for item in schedule["risks"] or ["无"])
    lines.extend(["", "## 需求映射", "", "| ID | 需求 | 来源 | 覆盖任务 |", "| --- | --- | --- | --- |"])
    for req in schedule["requirements"]:
        covered = [task["id"] for task in schedule["tasks"] if req["id"] in task["requirement_ids"]]
        lines.append(f"| {_md(req['id'])} | {_md(req['text'])} | {_md(req['source'])} | {_list_or_none(covered)} |")
    if not schedule["requirements"]:
        lines.append("| — | 无 | — | — |")
    lines.extend(["", "## 相对工作量排程", "", "| 任务 | 类型 | 相对起点 | 相对终点 | 工作量 | 依赖 | 资源 | 状态 |", "| --- | --- | ---: | ---: | ---: | --- | --- | --- |"])
    for task in schedule["tasks"]:
        status = "阻塞（外部条件待确认：" + _list_or_none(task["blocked_by"]) + "）" if task["status"] == "blocked" else "已排程"
        lines.append(
            f"| {_md(task['id'])} · {_md(task['title'])} | {task['kind']} | {_fmt_time(task['start'])} | "
            f"{_fmt_time(task['finish'])} | {_md(task['duration'])} | {_list_or_none(task['depends_on'])} | "
            f"{_list_or_none(task['resources'])} | {status} |"
        )
    lines.extend(["", "## 任务详情", ""])
    for task in schedule["tasks"]:
        lines.extend([
            f"### {_md(task['id'])} · {_md(task['title'])}", "", _md(task["description"]) or "无描述", "",
            f"- **交付物：** {_md(task['deliverable']) or '无'}",
            f"- **验收标准：** {_list_or_none(task['acceptance'])}",
            f"- **PR 边界：** {_md(task['pr_scope']) or '无'}",
            f"- **需求：** {_list_or_none(task['requirement_ids'])}",
            f"- **估算依据：** {_md(task['estimate_basis']) or '无'}",
            f"- **依赖：** {_list_or_none(task['depends_on'])}",
            f"- **资源锁：** {_list_or_none(task['resources'])}", "",
        ])
    return "\n".join(lines).rstrip() + "\n"


def render_svg(schedule: dict[str, Any], *, standalone: bool = True) -> str:
    tasks = schedule["tasks"]
    left, plot_width, right = 260, 760, 240
    row_height, top = 58, 148
    width, height = left + plot_width + right, max(280, top + row_height * len(tasks) + 90)
    makespan = max(float(schedule["scheduling"]["makespan"]), 1.0)
    esc = _html
    x_at = lambda value: left + (float(value) / makespan) * plot_width
    prefix = f'<?xml version="1.0" encoding="UTF-8"?>\n<!-- {GENERATED_MARKER} -->\n' if standalone else f'<!-- {GENERATED_MARKER} -->\n'
    parts = [prefix, f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img" aria-labelledby="chart-title chart-desc">',
             '<title id="chart-title">项目甘特图</title>',
             f'<desc id="chart-desc">{esc(schedule["title"])}。条长表示粗略相对工作量，横轴只表示抽象相对顺序，不对应现实时间；阻塞任务没有虚构相对偏移。</desc>',
             '<defs><linearGradient id="bg" x2="0" y2="1"><stop stop-color="#f8fafc"/><stop offset="1" stop-color="#eef2ff"/></linearGradient>',
             '<pattern id="blocked" width="8" height="8" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="8" height="8" fill="#fee2e2"/><line y2="8" stroke="#ef4444" stroke-width="2"/></pattern>',
             '<filter id="shadow"><feDropShadow dx="0" dy="2" stdDeviation="2" flood-opacity=".18"/></filter>',
             '<marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#64748b"/></marker></defs>',
             f'<rect width="{width}" height="{height}" rx="18" fill="url(#bg)"/>',
             f'<text x="28" y="38" font-family="Segoe UI,Arial,sans-serif" font-size="22" font-weight="700" fill="#0f172a">{esc(schedule["title"])}</text>',
             f'<text x="28" y="66" font-family="Segoe UI,Arial,sans-serif" font-size="13" fill="#475569">工作量单位：{esc(schedule["unit"])} · 条长=粗略工作量 · 横轴=相对位置 · 不代表实际工期</text>',
             '<g font-family="Segoe UI,Arial,sans-serif" font-size="12"><circle cx="30" cy="92" r="6" fill="#2563eb"/><text x="42" y="96" fill="#334155">任务（条长=工作量）</text><rect x="170" y="86" width="12" height="12" transform="rotate(45 176 92)" fill="#7c3aed"/><text x="190" y="96" fill="#334155">里程碑</text><circle cx="264" cy="92" r="6" fill="#0d9488"/><text x="276" y="96" fill="#334155">外部项</text><rect x="338" y="86" width="18" height="12" fill="url(#blocked)"/><text x="364" y="96" fill="#334155">阻塞状态（整行背景）</text></g>']
    ticks = min(10, max(2, int(math.ceil(makespan))))
    for i in range(ticks + 1):
        value = makespan * i / ticks
        x = x_at(value)
        parts.append(f'<line x1="{x:.2f}" y1="{top-20}" x2="{x:.2f}" y2="{top+row_height*len(tasks)}" stroke="#cbd5e1" stroke-dasharray="3 5"/>')
        parts.append(f'<text x="{x:.2f}" y="{top-28}" text-anchor="middle" font-family="Segoe UI,Arial,sans-serif" font-size="11" fill="#64748b">{esc(_fmt_time(value))}</text>')
    positions: dict[str, tuple[float, float]] = {}
    for i, task in enumerate(tasks):
        y = top + i * row_height
        parts.append(f'<rect x="18" y="{y}" width="{width-36}" height="{row_height-6}" rx="9" fill="{("#ffffff" if i % 2 == 0 else "#f8fafc")}" opacity=".72"/>')
        parts.append(f'<g class="task-row" data-task-id="{esc(task["id"])}"><title>{esc(task["id"])} — {esc(task["title"])}\n{esc(task["description"])}\n交付物：{esc(task["deliverable"])}\n验收：{esc("；".join(task["acceptance"]))}\nPR：{esc(task["pr_scope"])}</title>')
        label = _ellipsize(f'{task["id"]} · {task["title"]}', 29)
        deliverable = _ellipsize(task["deliverable"] or "无交付物描述", 35)
        parts.append(f'<text x="28" y="{y+21}" font-family="Segoe UI,Arial,sans-serif" font-size="13" font-weight="700" fill="#0f172a">{esc(label)}</text>')
        parts.append(f'<text x="28" y="{y+40}" font-family="Segoe UI,Arial,sans-serif" font-size="11" fill="#64748b">{esc(deliverable)}</text>')
        if task["status"] == "blocked":
            x, bar_width = left + 8, plot_width - 16
            parts.append(f'<rect x="{x}" y="{y+13}" width="{bar_width}" height="28" rx="7" fill="url(#blocked)"/>')
            parts.append(f'<text x="{x+12}" y="{y+32}" font-family="Segoe UI,Arial,sans-serif" font-size="12" font-weight="600" fill="#991b1b">阻塞：外部条件待确认（{esc(", ".join(task["blocked_by"]))}）</text>')
            positions[task["id"]] = (x, y + 27)
        elif task["duration"] == 0:
            x = x_at(task["start"])
            color = "#7c3aed" if task["kind"] == "milestone" else "#0d9488"
            parts.append(f'<rect x="{x-9:.2f}" y="{y+18}" width="18" height="18" rx="2" transform="rotate(45 {x:.2f} {y+27})" fill="{color}" filter="url(#shadow)"/>')
            if x > left + plot_width - 90:
                parts.append(f'<text x="{x-16:.2f}" y="{y+31}" text-anchor="end" font-family="Segoe UI,Arial,sans-serif" font-size="11" fill="#334155">{esc(_fmt_time(task["start"]))}</text>')
            else:
                parts.append(f'<text x="{x+16:.2f}" y="{y+31}" font-family="Segoe UI,Arial,sans-serif" font-size="11" fill="#334155">{esc(_fmt_time(task["start"]))}</text>')
            positions[task["id"]] = (x, y + 27)
        else:
            x1, x2 = x_at(task["start"]), x_at(task["finish"])
            color = "#0d9488" if task["kind"] == "external" else "#2563eb"
            bar_width = max(3, x2 - x1)
            parts.append(f'<rect x="{x1:.2f}" y="{y+14}" width="{bar_width:.2f}" height="26" rx="7" fill="{color}" filter="url(#shadow)"/>')
            time_label = f'{_fmt_time(task["start"])} → {_fmt_time(task["finish"])}'
            if bar_width >= 112:
                parts.append(f'<text x="{x1+7:.2f}" y="{y+31}" font-family="Segoe UI,Arial,sans-serif" font-size="11" font-weight="600" fill="white">{esc(time_label)}</text>')
            else:
                parts.append(f'<text x="{x2+7:.2f}" y="{y+31}" font-family="Segoe UI,Arial,sans-serif" font-size="10" font-weight="600" fill="#334155">{esc(time_label)}</text>')
            positions[task["id"]] = (x2, y + 27)
        details = f"需求 {', '.join(task['requirement_ids']) or '无'} · 资源 {', '.join(task['resources']) or '无'}"
        parts.append(f'<text x="{left+plot_width+18}" y="{y+22}" font-family="Segoe UI,Arial,sans-serif" font-size="11" fill="#334155">{esc(details[:34])}</text>')
        parts.append(f'<text x="{left+plot_width+18}" y="{y+39}" font-family="Segoe UI,Arial,sans-serif" font-size="10" fill="#64748b">工作量 {esc(task["duration"])}</text></g>')
    task_by_id = {task["id"]: task for task in tasks}
    for task in tasks:
        if task["status"] != "scheduled":
            continue
        child_y = top + task["input_index"] * row_height + 27
        child_x = x_at(task["start"])
        for dep in task["depends_on"]:
            parent = task_by_id[dep]
            if parent["status"] != "scheduled":
                continue
            parent_x = x_at(parent["finish"])
            parent_y = top + parent["input_index"] * row_height + 27
            bend = max(parent_x + 8, child_x - 12)
            parts.append(f'<path d="M {parent_x:.2f} {parent_y:.2f} H {bend:.2f} V {child_y:.2f} H {child_x-4:.2f}" fill="none" stroke="#64748b" stroke-width="1.4" stroke-dasharray="4 3" marker-end="url(#arrow)" opacity=".78"/>')
    blocked_count = sum(task["status"] == "blocked" for task in tasks)
    note = f"{blocked_count} 个任务因外部条件待确认而阻塞" if blocked_count else f"相对排程跨度：{_fmt_time(schedule['scheduling']['makespan'])}"
    parts.append(f'<text x="28" y="{height-28}" font-family="Segoe UI,Arial,sans-serif" font-size="12" fill="#475569">{esc(note)} · 箭头表示完成后依赖</text></svg>')
    return "".join(parts)


def render_html(schedule: dict[str, Any]) -> str:
    embedded = json.dumps(schedule, ensure_ascii=False, separators=(",", ":"), allow_nan=False)
    embedded = embedded.replace("&", "\\u0026").replace("<", "\\u003c").replace(">", "\\u003e").replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")
    svg = render_svg(schedule, standalone=False)
    capacity = "未知（按无上限排程）" if schedule["max_parallel"] is None else str(schedule["max_parallel"])
    blocked = any(task["status"] == "blocked" for task in schedule["tasks"])
    completion = (f"可排程相对终点 {_fmt_time(schedule['scheduling']['makespan'])}，整体相对终点未知"
                  if blocked else f"相对终点 {_fmt_time(schedule['scheduling']['makespan'])}")
    return f'''<!doctype html>
<!-- {GENERATED_MARKER} -->
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{_html(schedule["title"])}</title><style>
:root{{--ink:#0f172a;--muted:#64748b;--panel:#fff;--accent:#2563eb}}*{{box-sizing:border-box}}body{{margin:0;background:#e9eef7;color:var(--ink);font-family:"Segoe UI",system-ui,sans-serif}}main{{max-width:1320px;margin:auto;padding:32px}}header,.card{{background:rgba(255,255,255,.94);border:1px solid #dbe4f0;border-radius:18px;box-shadow:0 12px 38px #1e3a5f18}}header{{padding:28px}}h1{{margin:0 0 10px;font-size:30px}}p{{line-height:1.65}}.meta{{display:flex;gap:10px;flex-wrap:wrap}}.pill{{background:#eff6ff;color:#1d4ed8;padding:7px 11px;border-radius:999px;font-size:13px}}.card{{margin-top:20px;padding:20px}}.chart{{overflow:auto}}svg{{width:100%;min-width:1050px;height:auto}}.task-row{{cursor:pointer}}.task-row:hover{{opacity:.78}}.grid{{display:grid;grid-template-columns:1fr 1fr;gap:18px}}ul{{padding-left:22px}}table{{border-collapse:collapse;width:100%}}th,td{{padding:10px;text-align:left;border-bottom:1px solid #e2e8f0;vertical-align:top}}th{{color:#475569;font-size:12px;text-transform:uppercase}}button{{font:inherit;border:0;border-radius:8px;padding:8px 12px;background:#e2e8f0;cursor:pointer}}dialog{{max-width:700px;width:calc(100% - 40px);border:0;border-radius:18px;padding:24px;box-shadow:0 24px 80px #0f172a55}}dialog::backdrop{{background:#0f172a88}}.detail-grid{{display:grid;grid-template-columns:130px 1fr;gap:8px 14px}}.detail-grid dt{{font-weight:700;color:#475569}}.detail-grid dd{{margin:0;white-space:pre-wrap}}@media(max-width:800px){{main{{padding:14px}}.grid{{grid-template-columns:1fr}}}}
</style></head><body><main><header><h1>{_html(schedule["title"])}</h1><p>{_html(schedule["summary"])}</p><p>任务工作量为粗略估算；T+N 表示相对位置，不换算为小时、工作日或实际工期。条长表示工作量；阻塞任务的整行条纹只表示状态。</p><div class="meta"><span class="pill">工作量单位：{_html(schedule["unit"])}</span><span class="pill">并行容量：{_html(capacity)}</span><span class="pill">相对排程：{_html(completion)}</span></div></header>
<section class="card chart" aria-label="甘特图">{svg}</section>
<section class="grid"><div class="card"><h2>假设</h2><ul>{''.join('<li>'+_html(x)+'</li>' for x in schedule['assumptions']) or '<li>无</li>'}</ul></div><div class="card"><h2>风险</h2><ul>{''.join('<li>'+_html(x)+'</li>' for x in schedule['risks']) or '<li>无</li>'}</ul></div></section>
<section class="card"><h2>需求覆盖</h2><table><thead><tr><th>ID</th><th>需求</th><th>来源</th><th>覆盖任务</th></tr></thead><tbody>{''.join('<tr><td>'+_html(r['id'])+'</td><td>'+_html(r['text'])+'</td><td>'+_html(r['source'])+'</td><td>'+_html(', '.join(t['id'] for t in schedule['tasks'] if r['id'] in t['requirement_ids']))+'</td></tr>' for r in schedule['requirements']) or '<tr><td colspan="4">无需求</td></tr>'}</tbody></table></section>
<dialog id="details"><form method="dialog"><button style="float:right">关闭</button></form><h2 id="d-title"></h2><dl class="detail-grid" id="d-grid"></dl></dialog>
<script type="application/json" id="plan-data">{embedded}</script><script>
const plan=JSON.parse(document.getElementById('plan-data').textContent);const dlg=document.getElementById('details');const labels=[['状态','status'],['相对起点','start'],['相对终点','finish'],['工作量','duration'],['描述','description'],['交付物','deliverable'],['验收','acceptance'],['PR 边界','pr_scope'],['需求','requirement_ids'],['依赖','depends_on'],['资源锁','resources'],['估算依据','estimate_basis']];
const display=(key,value)=>{{if(key==='status')return value==='scheduled'?'已排程':'阻塞';if(key==='start'||key==='finish')return value==null?'—':'T+'+String(value);return Array.isArray(value)?value.join('、')||'无':String(value??'无')}};
document.querySelectorAll('.task-row').forEach(row=>row.addEventListener('click',()=>{{const t=plan.tasks.find(x=>x.id===row.dataset.taskId);document.getElementById('d-title').textContent=t.id+' · '+t.title;const grid=document.getElementById('d-grid');grid.replaceChildren();for(const [label,key] of labels){{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=display(key,t[key]);grid.append(dt,dd)}}dlg.showModal()}}));
</script></main></body></html>'''


def _is_ours(path: Path) -> bool:
    if not path.is_file():
        return False
    try:
        if path.name == "schedule.json":
            return json.loads(path.read_text(encoding="utf-8")).get("generator") == GENERATOR
        return GENERATED_MARKER in path.read_text(encoding="utf-8")[:1000]
    except (OSError, UnicodeError, json.JSONDecodeError, AttributeError):
        return False


def write_outputs(input_path: Path, output_dir: Path, schedule: dict[str, Any]) -> None:
    input_real = input_path.resolve()
    output_real = output_dir.resolve()
    if output_real == input_real:
        raise PlanError("输出目录不能与输入文件是同一路径")
    output_dir.mkdir(parents=True, exist_ok=True)
    if not output_dir.is_dir():
        raise PlanError(f"输出路径不是目录: {output_dir}")
    targets = {name: output_dir / name for name in OUTPUT_NAMES}
    for target in targets.values():
        if target.resolve() == input_real:
            raise PlanError(f"输入文件与输出产物路径冲突: {target}")
        if target.exists() and not _is_ours(target):
            raise PlanError(f"拒绝覆盖非本生成器产物: {target}")
    contents = {
        "schedule.json": json.dumps(schedule, ensure_ascii=False, indent=2, allow_nan=False) + "\n",
        "gantt.svg": render_svg(schedule),
        "gantt.html": render_html(schedule),
        "plan.md": render_markdown(schedule),
    }
    for name, content in contents.items():
        target = targets[name]
        temp_name = None
        try:
            with tempfile.NamedTemporaryFile("w", encoding="utf-8", newline="\n", dir=output_dir, delete=False) as handle:
                handle.write(content)
                temp_name = handle.name
            os.replace(temp_name, target)
        finally:
            if temp_name and os.path.exists(temp_name):
                os.unlink(temp_name)


def run(input_path: Path, output_dir: Path) -> dict[str, Any]:
    try:
        raw = json.loads(input_path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise PlanError(f"找不到输入文件: {input_path}") from exc
    except UnicodeDecodeError as exc:
        raise PlanError(f"输入文件必须是 UTF-8: {input_path}") from exc
    except json.JSONDecodeError as exc:
        raise PlanError(f"JSON 解析失败（第 {exc.lineno} 行，第 {exc.colno} 列）: {exc.msg}") from exc
    schedule = build_schedule(validate_plan(raw))
    write_outputs(input_path, output_dir, schedule)
    return schedule


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="校验项目计划并生成离线排程、甘特图和 Markdown。")
    parser.add_argument("input", type=Path, help="UTF-8 JSON 计划文件")
    parser.add_argument("--output", type=Path, required=True, help="输出目录")
    args = parser.parse_args(argv)
    try:
        schedule = run(args.input, args.output)
    except (PlanError, OSError) as exc:
        print(f"错误: {exc}", file=sys.stderr)
        return 2
    blocked = sum(task["status"] == "blocked" for task in schedule["tasks"])
    print(f"已生成 {len(OUTPUT_NAMES)} 个产物到 {args.output}；任务 {len(schedule['tasks'])}，阻塞 {blocked}。")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
